name: Deploy infrastructure for terraform-k8s-rancher project on prod account

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'environments/prod/**' 
  pull_request:
    branches:
      - main
    paths:
      - 'environments/prod/**'

permissions:
  id-token: write
  contents: read
jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
           terraform_version: "^1.3.7"
           terraform_wrapper: false
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::363664571315:role/role-prod-gitactions-Terraform
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
      - name: Initialise project and view terraform plan
        run: |
          cd environments/prod
          terraform fmt 
          terraform init 
          terraform plan

  deploy:
    name: Terraform Deploy
    needs: plan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
           terraform_version: "^1.3.7"
           terraform_wrapper: false
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::363664571315:role/role-prod-gitactions-Terraform
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
      - name: Initialise project and deploy terraform
        run: |
          cd environments/prod
          terraform fmt
          terraform init
          terraform apply --auto-approve=true